# exceptions.py for report_plus
class ReportPlusError(Exception): pass
